import { ShoesType } from "./types";

export const staticShoesData: ShoesType[] = [
  {
    id: "1",
    brandName: "Nike",
    product: [
      {
        id: "nike-1",
        name: "Nike Product 1",
        price: 100,
        pictures: ["/image/nike.png", "/image/nike.png", "/image/nike.png", "/image/nike.png"],
        color: ["Black", "White", "Red"],
        size: [7, 8, 9, 10, 11],
      },
      {
        id: "nike-2",
        name: "Nike Product 2",
        price: 110,
          pictures: ["/image/nike.png", "/image/nike.png", "/image/nike.png", "/image/nike.png"],
        color: ["Black", "White", "Red"],
        size: [7, 8, 9, 10, 11],
      },
      {
        id: "nike-3",
        name: "Nike Product 3",
        price: 120,
         pictures: ["/image/nike.png", "/image/nike.png", "/image/nike.png", "/image/nike.png"],
        color: ["Black", "White", "Red"],
        size: [7, 8, 9, 10, 11],
      },
      {
        id: "nike-4",
        name: "Nike Product 4",
        price: 130,
          pictures: ["/image/nike.png", "/image/nike.png", "/image/nike.png", "/image/nike.png"],
        color: ["Black", "White", "Red"],
        size: [7, 8, 9, 10, 11],
      },
      {
        id: "nike-5",
        name: "Nike Product 5",
        price: 140,
          pictures: ["/image/nike.png", "/image/nike.png", "/image/nike.png", "/image/nike.png"],
        color: ["Black", "White", "Red"],
        size: [7, 8, 9, 10, 11],
      },
      {
        id: "nike-6",
        name: "Nike Product 6",
        price: 150,
         pictures: ["/image/nike.png", "/image/nike.png", "/image/nike.png", "/image/nike.png"],
        color: ["Black", "White", "Red"],
        size: [7, 8, 9, 10, 11],
      },
      {
        id: "nike-7",
        name: "Nike Product 7",
        price: 160,
         pictures: ["/image/nike.png", "/image/nike.png", "/image/nike.png", "/image/nike.png"],
        color: ["Black", "White", "Red"],
        size: [7, 8, 9, 10, 11],
      },
      {
        id: "nike-8",
        name: "Nike Product 8",
        price: 170,
          pictures: ["/image/nike.png", "/image/nike.png", "/image/nike.png", "/image/nike.png"],
        color: ["Black", "White", "Red"],
        size: [7, 8, 9, 10, 11],
      },
    ],
  },
  {
    id: "2",
    brandName: "Adidas",
    product: [
      {
        id: "adidas-1",
        name: "Adidas Product 1",
        price: 120,
        pictures: ["/image/adida.webp", "/image/adida.webp","/image/adida.webp", "/image/adida.webp"],
        color: ["Blue", "Grey", "White"],
        size: [6, 7, 8, 9, 10],
      },
      {
        id: "adidas-2",
        name: "Adidas Product 2",
        price: 130,
       pictures: ["/image/adida.webp", "/image/adida.webp","/image/adida.webp", "/image/adida.webp"],
        color: ["Blue", "Grey", "White"],
        size: [6, 7, 8, 9, 10],
      },
      {
        id: "adidas-3",
        name: "Adidas Product 3",
        price: 140,
       pictures: ["/image/adida.webp", "/image/adida.webp","/image/adida.webp", "/image/adida.webp"],
        color: ["Blue", "Grey", "White"],
        size: [6, 7, 8, 9, 10],
      },
      {
        id: "adidas-4",
        name: "Adidas Product 4",
        price: 150,
        pictures: ["/image/adida.webp", "/image/adida.webp","/image/adida.webp", "/image/adida.webp"],
        color: ["Blue", "Grey", "White"],
        size: [6, 7, 8, 9, 10],
      },
      {
        id: "adidas-5",
        name: "Adidas Product 5",
        price: 160,
        pictures: ["/image/adida.webp", "/image/adida.webp","/image/adida.webp", "/image/adida.webp"],
        color: ["Blue", "Grey", "White"],
        size: [6, 7, 8, 9, 10],
      },
      {
        id: "adidas-6",
        name: "Adidas Product 6",
        price: 170,
        pictures: ["/image/adida.webp", "/image/adida.webp","/image/adida.webp", "/image/adida.webp"],
        color: ["Blue", "Grey", "White"],
        size: [6, 7, 8, 9, 10],
      },
      {
        id: "adidas-7",
        name: "Adidas Product 7",
        price: 180,
       pictures: ["/image/adida.webp", "/image/adida.webp","/image/adida.webp", "/image/adida.webp"],
        color: ["Blue", "Grey", "White"],
        size: [6, 7, 8, 9, 10],
      },
      {
        id: "adidas-8",
        name: "Adidas Product 8",
        price: 190,
       pictures: ["/image/adida.webp", "/image/adida.webp","/image/adida.webp", "/image/adida.webp"],
        color: ["Blue", "Grey", "White"],
        size: [6, 7, 8, 9, 10],
      },
    ],
  },
  {
    id: "3",
    brandName: "Puma",
    product: [
      {
        id: "puma-1",
        name: "Puma Product 1",
        price: 90,
        pictures: ["/image/puma.avif", "/image/puma.avif", "/image/puma.avif", "/image/puma.avif"],
        color: ["Green", "Black", "Yellow"],
        size: [8, 9, 10, 11, 12],
      },
      {
        id: "puma-2",
        name: "Puma Product 2",
        price: 100,
        pictures: ["/image/puma.avif", "/image/puma.avif", "/image/puma.avif", "/image/puma.avif"],
        color: ["Green", "Black", "Yellow"],
        size: [8, 9, 10, 11, 12],
      },
      {
        id: "puma-3",
        name: "Puma Product 3",
        price: 110,
        pictures: ["/image/puma.avif", "/image/puma.avif", "/image/puma.avif", "/image/puma.avif"],
        color: ["Green", "Black", "Yellow"],
        size: [8, 9, 10, 11, 12],
      },
      {
        id: "puma-4",
        name: "Puma Product 4",
        price: 120,
        pictures: ["/image/puma.avif", "/image/puma.avif", "/image/puma.avif", "/image/puma.avif"],
        color: ["Green", "Black", "Yellow"],
        size: [8, 9, 10, 11, 12],
      },
      {
        id: "puma-5",
        name: "Puma Product 5",
        price: 130,
        pictures: ["/image/puma.avif", "/image/puma.avif", "/image/puma.avif", "/image/puma.avif"],
        color: ["Green", "Black", "Yellow"],
        size: [8, 9, 10, 11, 12],
      },
      {
        id: "puma-6",
        name: "Puma Product 6",
        price: 140,
        pictures: ["/image/puma.avif", "/image/puma.avif", "/image/puma.avif", "/image/puma.avif"],
        color: ["Green", "Black", "Yellow"],
        size: [8, 9, 10, 11, 12],
      },
      {
        id: "puma-7",
        name: "Puma Product 7",
        price: 150,
       pictures: ["/image/puma.avif", "/image/puma.avif", "/image/puma.avif", "/image/puma.avif"],
        color: ["Green", "Black", "Yellow"],
        size: [8, 9, 10, 11, 12],
      },
      {
        id: "puma-8",
        name: "Puma Product 8",
        price: 160,
       pictures: ["/image/puma.avif", "/image/puma.avif", "/image/puma.avif", "/image/puma.avif"],
        color: ["Green", "Black", "Yellow"],
        size: [8, 9, 10, 11, 12],
      },
    ],
  },
];
